# Generated by Django 3.2.23 on 2024-01-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_URL',
            new_name='image_url',
        ),
    ]
